name: Build reprepro-multi-version for Debian

on:
  workflow_dispatch:
    inputs:
      reprepro-multi-version_version:
        description: The version of reprepro-multi-version to build.
        type: string
        required: true
      build_version:
        description: The build version.
        type: string
        required: true

permissions:
  contents: write

jobs:
  build-reprepro-multi-version:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout reprepro-multi-version-debian
        uses: actions/checkout@v4

      - name: Build reprepro-multi-version
        run: ./build.sh ${{ inputs.reprepro-multi-version_version }} ${{ inputs.build_version }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: reprepro-multi-version_*.deb


  release-reprepro-multi-version:
    name: (Draft-)Release reprepro-multi-version for Debian
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-reprepro-multi-version
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Publish Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: reprepro-multi-version_*.deb
          name: ${{ inputs.reprepro-multi-version_version }}+${{ inputs.build_version }}
          tag_name: ${{ env.RELEASE_TAG }}
          fail_on_unmatched_files: true
